### ISSUE TITLE
 Dimensions Not Compatible for makeSCE Multiplication

### ISSUE THREAD

**Issue by DarioS** [limfuxing/ruvIIInb#11]
`makeSCE` has error about array dimensions.

```r
> cancerAdjustedSCE <- makeSCE(cancerAdjusted, metaData)
  Error in mu * (out$psi[, batch]) : non-conformable arrays
```

I step through the code and see the error happens at ` dev <- (Ysub - mu)/sqrt(mu *(1 + mu * (out$psi[, batch])))` in `get.res`.

```r
> dim(mu)
  20157  5000
> dim(out$psi[, batch])
  20157 87680
> length(batch)
  87680
> table(batch)
    1     2     3     4     5     6 
18879 13042  7248 11693 15166 21652
```

I have specified six batches because this data set is comprised of single cell experiments done on six different dates. I see that batch is set in makeSCE to be the user's input: `batch <- obj$batch`.

The result object is 15.6 GB in size (87680 single cells), so I am not sure that I could easily share it for download. It looks like some matrix is being built up in chunks. But, the `batch` parameter is used without subsetting to the chunk being processed.

```r
> print(object.size(cancerAdjusted), units = "Gb")
  15.6 Gb
```

Hopefully I have provided enough detail to help pinpoint the issue without test data.

**Comment by limfuxing** [comment]
Thanks for this feedback. Can you tell me the dimension of out$psi? and did you specify batch.disp=TRUE?

**Comment by DarioS** [comment]
`batch.disp` is left as default `FALSE` for function `fastruvIII.nb`. Let me know if any different recommendation.
```r
> dim(out$psi)
  20157 6
```

**Comment by limfuxing** [comment]
I have updated the repo. I believe this issue is solved now. You might need to re-run fastruvIII.nb
