### ISSUE TITLE
makeSCE Default cData Causes Error

### ISSUE THREAD

**Issue by DarioS** [limfuxing/ruvIIInb#12]
Default is `cData = NULL`. This causes an error if the user executes `makeSCE` but doesn't specify a data frame to `cData`.

```r
Error in `rownames<-`(`*tmp*`, value = .get_colnames_from_first_assay(assays)) : 
  invalid rownames length
```

This error can be conceptually simplified to

```r
countsMini <- matrix(rpois(100, 100), ncol = 10)
colnames(countsMini) <- paste("Cell", 1:10)
rownames(countsMini) <- paste("Gene", 1:10)
SingleCellExperiment(assays = list(counts = countsMini), colData = NULL) # invalid rownames length error.
```

Perhaps clearly specify in documentation that `cData` is a mandatory user-specified parameter that is not allowed to be left `NULL` and also have a safety check inside the function.

```r
if(is.null(cData))
  stop("'cData' must be a user-specified data frame.")
```

**Comment by limfuxing** [comment]
I have added the safety check in the updated repo (v 0.7.8.6)

**Comment by DarioS** [comment]
Now stops immediately if `cData` is not user-provided.
