### ISSUE TITLE
Error in h(simpleError(msg, call)) :  in fastruvIII.nb using use.pseudosample=TRUE

### ISSUE THREAD

**Issue by zpingfeng** [limfuxing/ruvIIInb#2]
Thanks for developing such nice package. I tested with demo data, but got an error message when I run fastruvIII.nb using use.pseudosample=TRUE. Please see details below:

> ruv3nb_out_ps<-fastruvIII.nb(Y=DelayedArray(assays(sce)$counts),
+                              M=diag(dim(sce)[2]),
+                              ctl=rowData(sce)$ctlLogical,
+                              k=2,
+                              use.pseudosample=TRUE, #Indicating whether pseudo-cells are to be used to to define pseudo-replicates
+                              batch=rep(1,dim(sce)[2])# NSCLC data comes from a single batch
+ )
[1] "time to Winsorize count matrix:30.7759969234467"
[1] "8409genes with all zero counts are removed following a Winsorization step."
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'object' in selecting a method for function 'na.omit': invalid number of intervals

**Comment by limfuxing** [comment]
Thanks for trying the package out. I think the command in the vignette is incorrect (I will also check this with the vignette developer). Could you first create the M matrix by following section 2.3.0.2 and 2.3.0.3? Once you have the M matrix, run the following command 
    ruv3nb_out_ps<-fastruvIII.nb(Y=DelayedArray(assays(sce)$counts),M=M,
                             ctl=rowData(sce)$ctlLogical,k=2,use.pseudosample=TRUE,batch=rep(1,dim(sce)[2])

We realise that the step for creating M matrix is currently a bit clunky and we plan to release a major upgrade in early January where M matrix will be created inside the fastruvIII.nb function so users do not need to manually create it. The new version will also be faster with better memory management.

**Comment by zpingfeng** [comment]
Thanks for the reply!  M=M (defined earlier ) is ok, but not work with M=diag(dim(sce)[2]) as shown in the demo.

**Comment by limfuxing** [comment]
Good to know. Just fyi, the results with M=M and use.pseudosample=TRUE have already incorporated pseudocells on top of the pseudo-replicates defined by the original M matrix. I will talk to the vignette developer to amend the codes shown in the demo
