### ISSUE TITLE
Devtools Installation Fails

### ISSUE THREAD

**Issue by DarioS** [limfuxing/ruvIIInb#4]
I have never had a problem installing an R package from GitHub until this.
```r
library(devtools)
> install_github("limfuxing/ruvIIInb", build_vignettes = FALSE)
Downloading GitHub repo limfuxing/ruvIIInb@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/limfuxing/ruvIIInb/tarball/HEAD' failed
```
Can this major problem be fixed?
```r
> sessionInfo()
R version 4.2.3 (2023-03-15 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

locale:
[1] LC_COLLATE=English_Australia.utf8 LC_CTYPE=English_Australia.utf8 LC_MONETARY=English_Australia.utf8 LC_NUMERIC=C
[5] LC_TIME=English_Australia.utf8  
```

It is likely caused by the unusually large size of the package (238 MB).

**Comment by limfuxing** [comment]
Hi Dario, thanks for the feedback. We never had this issue previously, although it did take a while to install due to the size of the package. We are short of manpower currently but will look to reduce package size when we update

**Comment by DarioS** [comment]
This error happens at home but not at work. I suppose that it is some kind of timeout on a slower internet connection. A workaround for anyone else who has the same experience is `options(timeout = 600)`. That changes the timeout threshold to 600 seconds (10 minutes) instead of the default of 60 seconds (1 minute) and then the installation succeeds at home. But, it would be nice to make the package smaller, regardless.

**Comment by limfuxing** [comment]
@DarioS  thanks for your feedback. I have now removed the presaved data from the repo. The package is much faster to install now
