### ISSUE TITLE
Some Genes Indentified As All-zero But Have Non-zero Counts

### ISSUE THREAD

**Issue by DarioS** [limfuxing/ruvIIInb#9]
The processing removes four thousand genes. However, I have already removed all genes which are all zero counts before RUV-III.

```r
> sum(rowSums(delayedCounts) == 0) # All all-zero genes were already removed.
  0
RUV3adjust <- fastruvIII.nb(delayedCounts, replicates, controls, ncores = 8)
[1] "time to Winsorize count matrix:463.026260614395"
[1] "4084genes with all zero counts are removed following a Winsorization step."
```
I don't think Winsorization would introduce zero counts for non-zero values. I wonder why it happens.

**Comment by limfuxing** [comment]
The current winsorization step will 'clip' the count at 99.5th percentile for each gene. If 99.5% or more cells have zero counts for a gene, then the maximum count for that gene is set to zero. In other words, to 'survive' the winsorization step with nonzero counts, a gene needs to be expressed in at least 0.5% of the cells.
